# Generated by Django 5.0.6 on 2024-06-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('categoria', models.TextField()),
                ('autor', models.CharField(max_length=10)),
                ('precion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('likes', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
